[package]
name = "musik"
version = "0.1.0"
edition = "2021"
authors = ["Ivan L <tsionyx@gmail.com>"]
keywords = ["music"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
