# https://github.com/actions-rs/example/blob/master/.github/workflows/audit.yml
name: Security audit

on:
  schedule:
    # every 5th day
    # https://crontab.guru/#0_0_1/5_*_*
    - cron: '0 0 1/5 * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cargo-audit binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true

      - name: Run cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          # args: --ignore=RUSTSEC-2023-0071

      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
